<div class="container ">
		<div class="row margin-bottom-40">
			<div class="col-md-8">
					<b>Bina Marga</b><br><br>
					<p class="text-justify">Bidang  Bina  Marga  dipimpin  oleh  Kepala  Bidang  yang  mempunyai  tugas  melaksanakan penyiapan  perumusan  kebijakan  teknis  dan  pelaksanaan  kebijakan  bidang  Bina  Marga.  Untuk menyelenggaran tugas tersebut Bidang Bina Marga mempunyai fungsi :</p>
					<table>
						<tr><td>1.</td><td>Penyusunan perencanaan program bidang bina marga;</td></tr>
						<tr><td>2.</td><td>Perumusan dan pelaksanaan kebijakan teknis dibidang;</td></tr>
						<tr><td>3.</td><td>Koordinasi dan pembinaan pelaksanaan kegiatan bina marga;</td></tr>
						<tr><td>4.</td><td>penyelenggaraan kegiatan urusan pembangunan dan peningkatan jalan, pemeliharaan jaringan jalan dan Pembangunan dan Rehabilitasi Jembatan;</td></tr>
						<tr><td>5.</td><td>pengawasan, pengendalian, evaluasi dan pelaporan pelaksanaan kegiatan pembangunan danpeningkatan  jalan, pemeliharaan  jaringan  jalan  dan  Pembangunan dan Rehabilitasi Jembatan;</td></tr>
						<tr><td>6.</td><td>penyusunan pelaporan kinerja Bidang; dan/ atau</td></tr>
						<tr><td>7.</td><td>pelaksanaan  tugas  kedinasan  lain  yang  diperintahkan  atasan  sesuai  dengan  bidang tugas dan fungsinya.</td></tr>
					</table><br>
					<p class="text-justify">Dalam melaksanakan  fungsi  di  atas,  Kepala  Bidang  dibantu  oleh  3  (tiga)  orang  Kepala Seksi, yaitu:</p>
						<p><b>1.Seksi Pembangunan dan Peningkatan Jalan</b></p>
						<p class="text-justify">Seksi  Pembangunan  dan  Peningkatan  Jalan  mempunyai  tugas  melakukan  penyiapan bahan perencanaan, perumasan  kebijakan  teknis,  pembinaan  dan  koordinasi serta  pelaksanaan pembangunan dan peningkatan jalan. Untuk melaksanakan tugas sebagaimana dimaksud Seksi pembangunan dan peningkatan jalan menyelenggarakan fungsi :
					</p>
					<table>
						<tr><td>a.</td><td class="text-justify">penyiapan  bahan  penyusunan  perencanaan  program  dan  kegiatan  pembangunan  dan peningkatan jalan;</td></tr>
						<tr><td>b.</td><td class="text-justify">perumusan kebijakan teknis dibidang pembangunan dan peningkatan jalan;</td></tr>
						<tr><td>c.</td><td class="text-justify">pembinaan, pengawasan dan  koordinasi pelaksanaan pembangunan dan peningkatan jalan;</td></tr>
						<tr><td>d.</td><td class="text-justify">melakukan pengaturan jalan Kabupaten Padang Pariaman</td></tr>
						<tr><td>e.</td><td class="text-justify">pelaksanaan pembinaan jalan kabupaten;</td></tr>
						<tr><td>f.</td><td class="text-justify">pelaksanaan pengembangan teknologi terapan dibidang jalan untuk jalan kabupaten</td></tr>
						<tr><td>g.</td><td class="text-justify">pelaksanaan  pembangunan  jalan  dalam  bentuk  pembiayaan,  perencanaan  teknis, pemprograman  dan  penganggaran,  pengadaan  lahan,  serta  pelaksanaan  konstruksi jalan  kabupaten,  pengoperasian  dan  pengembangan  pengelolaan  manajemen  jalan kabupaten</td></tr>
						<tr><td>h.</td><td class="text-justify">penyiapan pembiayaan pembangunan dan peningkatan jalan kabupaten</td></tr>
						<tr><td>i.</td><td class="text-justify">pelaksanaan  pembangunan  jalan  dalam  bentuk  pembiayaan,  perencanaan  teknis, pemprograman  dan  penganggaran,  pengadaan  lahan,  serta  pelaksanaan  konstruksi jalan  kabupaten,  pengoperasian  dan  pengembangan  pengelolaan  manajemen  jalan kabupaten;</td></tr>
						<tr><td>j.</td><td class="text-justify">pelaksanaanpengembangan dan pengelolaan manajemen jalan kabupaten</td></tr>
						<tr><td>k.</td>penyiapan bahan pelaksanaan monitoring dan evaluasi pelaksanaan kegiatan dibidang pembangunan dan peningkatan jalan;<td class="text-justify"></td></tr>
						<tr><td>l.</td><td class="text-justify">pelaporan pelaksanaan kegiatan; dan/ atau</td></tr>
						<tr><td>m.</td><td class="text-justify">pelaksanaan  tugas  kedinasan  lain  yang  diperintahkan  atasan  sesuai  dengan  bidang tugas dan fungsinya</td></tr>
					</table><br>
					<p><b>2. Seksi Pemeliharaan Jaringan Jalan</b></p>
					<p class="text-justify">Seksi   Pemeliharaan   Jaringan   Jalan   mempunyai   tugas   melakukan   penyiapan   bahan perencanaan,   perumusan   kebijakan   teknis,   pembinaan dan   koordinasi   serta   pelaksanaan pemeliharaan   jaringan   jalan.   Untuk   melaksanakan   tugas   sebagaimana   dimaksud   Seksi pemeliharaan jaringan jalan menyelenggarakan fungsi:</p>
					<table>
						<tr><td></td>a.<td>penyiapan   bahan   penyusunan   perencanaan   program   dan   kegiatan   pemeliharaan jaringan jalan;</td></tr>
						<tr><td></td>b.<td>perumusan kebijakan teknis dibidang pemeliharaan jaringan jalan;</td></tr>
						<tr><td></td>c.<td>pembinaan, pengawasan dan  koordinasi pelaksanaan pemeliharaan jaringan jalan;</td></tr>
						<tr><td></td>d.<td>penyiapan   bahan   penyusunan   perencanaan   program   dan   kegiatan   pemeliharaan jaringan jalan;perumusan kebijakan teknis dibidang pemeliharaan jaringan jalan;pembinaan, pengawasan dan  koordinasi pelaksanaan pemeliharaan jaringan jalan;penyusunan perencanaan umum dan pembiayaan jaringan jalan;pengoperasian dan pemeliharaan jaringan jalan;pelaksanaan    Perumusan    kebijakan    dan    penyelenggaraan    pemeliharaan    jalan berdasarkan  kebijakan  nasional  dibidangjalan  dengan  memperhatikan  keserasian antar    daerah,    dan    antar    kawasan    serta    penyusunan    pedoman    operasional penyelenggaraan pemeliharaan jalan dan jembatan;penyusunan   rencana   teknis,   pemograman   dan   penganggaran,   sertapelaksanaan pemeliharaan konstruksi jalan dan jembatan;perhitungan   rencana   anggaran   biaya   pemeliharaan   sarana   prasarana   jalan   dan jembatan;pelaksanaan    evaluasi    dan    pembuatan    laporan    pelaksanaan    urusan    dibidang pemeliharaan jalan dan jembatan;penanggulangan jalan dan jembatan yang rusak akibat bencana alam;pelaksanaan penyusunan dan penetapan kelas jalan pada jaringan jalan kabupaten;penyiapan bahan pelaksanaan monitoring dan evaluasi pelaksanaan kegiatan dibidang Pemeliharaan Jaringan Jalan;pelaporan pelaksanaan kegiatan; dan/ataupelaksanaan  tugas  kedinasan  lain  yang  diperintahkan  atasan  sesuai  dengan  bidang tugas dan fungsinya</td></tr>
						<tr><td></td>e.<td>penyiapan   bahan   penyusunan   perencanaan   program   dan   kegiatan   pemeliharaan jaringan jalan;perumusan kebijakan teknis dibidang pemeliharaan jaringan jalan;pembinaan, pengawasan dan  koordinasi pelaksanaan pemeliharaan jaringan jalan;penyusunan perencanaan umum dan pembiayaan jaringan jalan;pengoperasian dan pemeliharaan jaringan jalan;pelaksanaan    Perumusan    kebijakan    dan    penyelenggaraan    pemeliharaan    jalan berdasarkan  kebijakan  nasional  dibidangjalan  dengan  memperhatikan  keserasian antar    daerah,    dan    antar    kawasan    serta    penyusunan    pedoman    operasional penyelenggaraan pemeliharaan jalan dan jembatan;penyusunan   rencana   teknis,   pemograman   dan   penganggaran,   sertapelaksanaan pemeliharaan konstruksi jalan dan jembatan;perhitungan   rencana   anggaran   biaya   pemeliharaan   sarana   prasarana   jalan   dan jembatan;pelaksanaan    evaluasi    dan    pembuatan    laporan    pelaksanaan    urusan    dibidang pemeliharaan jalan dan jembatan;penanggulangan jalan dan jembatan yang rusak akibat bencana alam;pelaksanaan penyusunan dan penetapan kelas jalan pada jaringan jalan kabupaten;penyiapan bahan pelaksanaan monitoring dan evaluasi pelaksanaan kegiatan dibidang Pemeliharaan Jaringan Jalan;pelaporan pelaksanaan kegiatan; dan/ataupelaksanaan  tugas  kedinasan  lain  yang  diperintahkan  atasan  sesuai  dengan  bidang tugas dan fungsinya</td></tr>
						<tr><td></td>f.<td>penyiapan   bahan   penyusunan   perencanaan   program   dan   kegiatan   pemeliharaan jaringan jalan;perumusan kebijakan teknis dibidang pemeliharaan jaringan jalan;pembinaan, pengawasan dan  koordinasi pelaksanaan pemeliharaan jaringan jalan;penyusunan perencanaan umum dan pembiayaan jaringan jalan;pengoperasian dan pemeliharaan jaringan jalan;pelaksanaan    Perumusan    kebijakan    dan    penyelenggaraan    pemeliharaan    jalan berdasarkan  kebijakan  nasional  dibidangjalan  dengan  memperhatikan  keserasian antar    daerah,    dan    antar    kawasan    serta    penyusunan    pedoman    operasional penyelenggaraan pemeliharaan jalan dan jembatan;penyusunan   rencana   teknis,   pemograman   dan   penganggaran,   sertapelaksanaan pemeliharaan konstruksi jalan dan jembatan;perhitungan   rencana   anggaran   biaya   pemeliharaan   sarana   prasarana   jalan   dan jembatan;pelaksanaan    evaluasi    dan    pembuatan    laporan    pelaksanaan    urusan    dibidang pemeliharaan jalan dan jembatan;penanggulangan jalan dan jembatan yang rusak akibat bencana alam;pelaksanaan penyusunan dan penetapan kelas jalan pada jaringan jalan kabupaten;penyiapan bahan pelaksanaan monitoring dan evaluasi pelaksanaan kegiatan dibidang Pemeliharaan Jaringan Jalan;pelaporan pelaksanaan kegiatan; dan/ataupelaksanaan  tugas  kedinasan  lain  yang  diperintahkan  atasan  sesuai  dengan  bidang tugas dan fungsinya</td></tr>
						<tr><td></td>g.<td>penyiapan   bahan   penyusunan   perencanaan   program   dan   kegiatan   pemeliharaan jaringan jalan;perumusan kebijakan teknis dibidang pemeliharaan jaringan jalan;pembinaan, pengawasan dan  koordinasi pelaksanaan pemeliharaan jaringan jalan;penyusunan perencanaan umum dan pembiayaan jaringan jalan;pengoperasian dan pemeliharaan jaringan jalan;pelaksanaan    Perumusan    kebijakan    dan    penyelenggaraan    pemeliharaan    jalan berdasarkan  kebijakan  nasional  dibidangjalan  dengan  memperhatikan  keserasian antar    daerah,    dan    antar    kawasan    serta    penyusunan    pedoman    operasional penyelenggaraan pemeliharaan jalan dan jembatan;penyusunan   rencana   teknis,   pemograman   dan   penganggaran,   sertapelaksanaan pemeliharaan konstruksi jalan dan jembatan;perhitungan   rencana   anggaran   biaya   pemeliharaan   sarana   prasarana   jalan   dan jembatan;pelaksanaan    evaluasi    dan    pembuatan    laporan    pelaksanaan    urusan    dibidang pemeliharaan jalan dan jembatan;penanggulangan jalan dan jembatan yang rusak akibat bencana alam;pelaksanaan penyusunan dan penetapan kelas jalan pada jaringan jalan kabupaten;penyiapan bahan pelaksanaan monitoring dan evaluasi pelaksanaan kegiatan dibidang Pemeliharaan Jaringan Jalan;pelaporan pelaksanaan kegiatan; dan/ataupelaksanaan  tugas  kedinasan  lain  yang  diperintahkan  atasan  sesuai  dengan  bidang tugas dan fungsinya</td></tr>
						<tr><td></td>h.<td>penyiapan   bahan   penyusunan   perencanaan   program   dan   kegiatan   pemeliharaan jaringan jalan;perumusan kebijakan teknis dibidang pemeliharaan jaringan jalan;pembinaan, pengawasan dan  koordinasi pelaksanaan pemeliharaan jaringan jalan;penyusunan perencanaan umum dan pembiayaan jaringan jalan;pengoperasian dan pemeliharaan jaringan jalan;pelaksanaan    Perumusan    kebijakan    dan    penyelenggaraan    pemeliharaan    jalan berdasarkan  kebijakan  nasional  dibidangjalan  dengan  memperhatikan  keserasian antar    daerah,    dan    antar    kawasan    serta    penyusunan    pedoman    operasional penyelenggaraan pemeliharaan jalan dan jembatan;penyusunan   rencana   teknis,   pemograman   dan   penganggaran,   sertapelaksanaan pemeliharaan konstruksi jalan dan jembatan;perhitungan   rencana   anggaran   biaya   pemeliharaan   sarana   prasarana   jalan   dan jembatan;pelaksanaan    evaluasi    dan    pembuatan    laporan    pelaksanaan    urusan    dibidang pemeliharaan jalan dan jembatan;penanggulangan jalan dan jembatan yang rusak akibat bencana alam;pelaksanaan penyusunan dan penetapan kelas jalan pada jaringan jalan kabupaten;penyiapan bahan pelaksanaan monitoring dan evaluasi pelaksanaan kegiatan dibidang Pemeliharaan Jaringan Jalan;pelaporan pelaksanaan kegiatan; dan/ataupelaksanaan  tugas  kedinasan  lain  yang  diperintahkan  atasan  sesuai  dengan  bidang tugas dan fungsinya</td></tr>
						<tr><td></td>i.<td>penyiapan   bahan   penyusunan   perencanaan   program   dan   kegiatan   pemeliharaan jaringan jalan;perumusan kebijakan teknis dibidang pemeliharaan jaringan jalan;pembinaan, pengawasan dan  koordinasi pelaksanaan pemeliharaan jaringan jalan;penyusunan perencanaan umum dan pembiayaan jaringan jalan;pengoperasian dan pemeliharaan jaringan jalan;pelaksanaan    Perumusan    kebijakan    dan    penyelenggaraan    pemeliharaan    jalan berdasarkan  kebijakan  nasional  dibidangjalan  dengan  memperhatikan  keserasian antar    daerah,    dan    antar    kawasan    serta    penyusunan    pedoman    operasional penyelenggaraan pemeliharaan jalan dan jembatan;penyusunan   rencana   teknis,   pemograman   dan   penganggaran,   sertapelaksanaan pemeliharaan konstruksi jalan dan jembatan;perhitungan   rencana   anggaran   biaya   pemeliharaan   sarana   prasarana   jalan   dan jembatan;pelaksanaan    evaluasi    dan    pembuatan    laporan    pelaksanaan    urusan    dibidang pemeliharaan jalan dan jembatan;penanggulangan jalan dan jembatan yang rusak akibat bencana alam;pelaksanaan penyusunan dan penetapan kelas jalan pada jaringan jalan kabupaten;penyiapan bahan pelaksanaan monitoring dan evaluasi pelaksanaan kegiatan dibidang Pemeliharaan Jaringan Jalan;pelaporan pelaksanaan kegiatan; dan/ataupelaksanaan  tugas  kedinasan  lain  yang  diperintahkan  atasan  sesuai  dengan  bidang tugas dan fungsinya</td></tr>
						<tr><td></td>j.<td>penyiapan   bahan   penyusunan   perencanaan   program   dan   kegiatan   pemeliharaan jaringan jalan;perumusan kebijakan teknis dibidang pemeliharaan jaringan jalan;pembinaan, pengawasan dan  koordinasi pelaksanaan pemeliharaan jaringan jalan;penyusunan perencanaan umum dan pembiayaan jaringan jalan;pengoperasian dan pemeliharaan jaringan jalan;pelaksanaan    Perumusan    kebijakan    dan    penyelenggaraan    pemeliharaan    jalan berdasarkan  kebijakan  nasional  dibidangjalan  dengan  memperhatikan  keserasian antar    daerah,    dan    antar    kawasan    serta    penyusunan    pedoman    operasional penyelenggaraan pemeliharaan jalan dan jembatan;penyusunan   rencana   teknis,   pemograman   dan   penganggaran,   sertapelaksanaan pemeliharaan konstruksi jalan dan jembatan;perhitungan   rencana   anggaran   biaya   pemeliharaan   sarana   prasarana   jalan   dan jembatan;pelaksanaan    evaluasi    dan    pembuatan    laporan    pelaksanaan    urusan    dibidang pemeliharaan jalan dan jembatan;penanggulangan jalan dan jembatan yang rusak akibat bencana alam;pelaksanaan penyusunan dan penetapan kelas jalan pada jaringan jalan kabupaten;penyiapan bahan pelaksanaan monitoring dan evaluasi pelaksanaan kegiatan dibidang Pemeliharaan Jaringan Jalan;pelaporan pelaksanaan kegiatan; dan/ataupelaksanaan  tugas  kedinasan  lain  yang  diperintahkan  atasan  sesuai  dengan  bidang tugas dan fungsinya</td></tr>
						<tr><td></td>k.<td>penyiapan   bahan   penyusunan   perencanaan   program   dan   kegiatan   pemeliharaan jaringan jalan;perumusan kebijakan teknis dibidang pemeliharaan jaringan jalan;pembinaan, pengawasan dan  koordinasi pelaksanaan pemeliharaan jaringan jalan;penyusunan perencanaan umum dan pembiayaan jaringan jalan;pengoperasian dan pemeliharaan jaringan jalan;pelaksanaan    Perumusan    kebijakan    dan    penyelenggaraan    pemeliharaan    jalan berdasarkan  kebijakan  nasional  dibidangjalan  dengan  memperhatikan  keserasian antar    daerah,    dan    antar    kawasan    serta    penyusunan    pedoman    operasional penyelenggaraan pemeliharaan jalan dan jembatan;penyusunan   rencana   teknis,   pemograman   dan   penganggaran,   sertapelaksanaan pemeliharaan konstruksi jalan dan jembatan;perhitungan   rencana   anggaran   biaya   pemeliharaan   sarana   prasarana   jalan   dan jembatan;pelaksanaan    evaluasi    dan    pembuatan    laporan    pelaksanaan    urusan    dibidang pemeliharaan jalan dan jembatan;penanggulangan jalan dan jembatan yang rusak akibat bencana alam;pelaksanaan penyusunan dan penetapan kelas jalan pada jaringan jalan kabupaten;penyiapan bahan pelaksanaan monitoring dan evaluasi pelaksanaan kegiatan dibidang Pemeliharaan Jaringan Jalan;pelaporan pelaksanaan kegiatan; dan/ataupelaksanaan  tugas  kedinasan  lain  yang  diperintahkan  atasan  sesuai  dengan  bidang tugas dan fungsinya</td></tr>
						<tr><td></td>l.<td>penyiapan   bahan   penyusunan   perencanaan   program   dan   kegiatan   pemeliharaan jaringan jalan;perumusan kebijakan teknis dibidang pemeliharaan jaringan jalan;pembinaan, pengawasan dan  koordinasi pelaksanaan pemeliharaan jaringan jalan;penyusunan perencanaan umum dan pembiayaan jaringan jalan;pengoperasian dan pemeliharaan jaringan jalan;pelaksanaan    Perumusan    kebijakan    dan    penyelenggaraan    pemeliharaan    jalan berdasarkan  kebijakan  nasional  dibidangjalan  dengan  memperhatikan  keserasian antar    daerah,    dan    antar    kawasan    serta    penyusunan    pedoman    operasional penyelenggaraan pemeliharaan jalan dan jembatan;penyusunan   rencana   teknis,   pemograman   dan   penganggaran,   sertapelaksanaan pemeliharaan konstruksi jalan dan jembatan;perhitungan   rencana   anggaran   biaya   pemeliharaan   sarana   prasarana   jalan   dan jembatan;pelaksanaan    evaluasi    dan    pembuatan    laporan    pelaksanaan    urusan    dibidang pemeliharaan jalan dan jembatan;penanggulangan jalan dan jembatan yang rusak akibat bencana alam;pelaksanaan penyusunan dan penetapan kelas jalan pada jaringan jalan kabupaten;penyiapan bahan pelaksanaan monitoring dan evaluasi pelaksanaan kegiatan dibidang Pemeliharaan Jaringan Jalan;pelaporan pelaksanaan kegiatan; dan/ataupelaksanaan  tugas  kedinasan  lain  yang  diperintahkan  atasan  sesuai  dengan  bidang tugas dan fungsinya</td></tr>
						<tr><td></td>m.<td>penyiapan   bahan   penyusunan   perencanaan   program   dan   kegiatan   pemeliharaan jaringan jalan;perumusan kebijakan teknis dibidang pemeliharaan jaringan jalan;pembinaan, pengawasan dan  koordinasi pelaksanaan pemeliharaan jaringan jalan;penyusunan perencanaan umum dan pembiayaan jaringan jalan;pengoperasian dan pemeliharaan jaringan jalan;pelaksanaan    Perumusan    kebijakan    dan    penyelenggaraan    pemeliharaan    jalan berdasarkan  kebijakan  nasional  dibidangjalan  dengan  memperhatikan  keserasian antar    daerah,    dan    antar    kawasan    serta    penyusunan    pedoman    operasional penyelenggaraan pemeliharaan jalan dan jembatan;penyusunan   rencana   teknis,   pemograman   dan   penganggaran,   sertapelaksanaan pemeliharaan konstruksi jalan dan jembatan;perhitungan   rencana   anggaran   biaya   pemeliharaan   sarana   prasarana   jalan   dan jembatan;pelaksanaan    evaluasi    dan    pembuatan    laporan    pelaksanaan    urusan    dibidang pemeliharaan jalan dan jembatan;penanggulangan jalan dan jembatan yang rusak akibat bencana alam;pelaksanaan penyusunan dan penetapan kelas jalan pada jaringan jalan kabupaten;penyiapan bahan pelaksanaan monitoring dan evaluasi pelaksanaan kegiatan dibidang Pemeliharaan Jaringan Jalan;pelaporan pelaksanaan kegiatan; dan/ataupelaksanaan  tugas  kedinasan  lain  yang  diperintahkan  atasan  sesuai  dengan  bidang tugas dan fungsinya</td></tr>
						<tr><td></td>n.<td>penyiapan   bahan   penyusunan   perencanaan   program   dan   kegiatan   pemeliharaan jaringan jalan;perumusan kebijakan teknis dibidang pemeliharaan jaringan jalan;pembinaan, pengawasan dan  koordinasi pelaksanaan pemeliharaan jaringan jalan;penyusunan perencanaan umum dan pembiayaan jaringan jalan;pengoperasian dan pemeliharaan jaringan jalan;pelaksanaan    Perumusan    kebijakan    dan    penyelenggaraan    pemeliharaan    jalan berdasarkan  kebijakan  nasional  dibidangjalan  dengan  memperhatikan  keserasian antar    daerah,    dan    antar    kawasan    serta    penyusunan    pedoman    operasional penyelenggaraan pemeliharaan jalan dan jembatan;penyusunan   rencana   teknis,   pemograman   dan   penganggaran,   sertapelaksanaan pemeliharaan konstruksi jalan dan jembatan;perhitungan   rencana   anggaran   biaya   pemeliharaan   sarana   prasarana   jalan   dan jembatan;pelaksanaan    evaluasi    dan    pembuatan    laporan    pelaksanaan    urusan    dibidang pemeliharaan jalan dan jembatan;penanggulangan jalan dan jembatan yang rusak akibat bencana alam;pelaksanaan penyusunan dan penetapan kelas jalan pada jaringan jalan kabupaten;penyiapan bahan pelaksanaan monitoring dan evaluasi pelaksanaan kegiatan dibidang Pemeliharaan Jaringan Jalan;pelaporan pelaksanaan kegiatan; dan/ataupelaksanaan  tugas  kedinasan  lain  yang  diperintahkan  atasan  sesuai  dengan  bidang tugas dan fungsinya</td></tr>
					</table>
		</div>
			<div class="col-md-4 col-sm-4">
			<div class="card bg-light mb-3" style="width: 38rem;">
				<img src="<?= theme();?>img/bg.PNG" style="width: 400px;height: 200px">
			</div>
			</div>
		</div>
	</div>
